const {chromium}=require('playwright');
const fs=require('node:fs');const assert=require('node:assert/strict');
const path=require('node:path');const ROOT=path.resolve(__dirname,'..');const OUT=path.join(ROOT,'test-results');fs.mkdirSync(OUT,{recursive:true});
const passed=[],errors=[];const ok=n=>{passed.push(n);console.log('PASS',n)};
(async()=>{const {preview}=await import('vite');const server=await preview({root:ROOT,preview:{host:'127.0.0.1',port:5173,strictPort:true}});const browser=await chromium.launch({executablePath:process.env.ARTURA_CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});let page;
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},baseURL:'http://127.0.0.1:5173'});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(8000);
 const go=async path=>{await page.goto(path)};const button=name=>page.getByRole('button',{name,exact:true});const lang=async code=>{await button(code).first().click();await page.waitForFunction(v=>document.documentElement.lang===v,code.toLowerCase())};const db=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('artura.store.v2')));
 await go('/');await lang('ID');await page.getByRole('link',{name:'Beranda',exact:true}).waitFor();assert.ok((await page.locator('main').innerText()).includes('Karya dengan karakter.'));await lang('EN');assert.ok((await page.locator('main').innerText()).includes('Art with character.'));ok('Home EN/ID translations and document language');
 const texts={};for(const route of ['/','/portfolio','/shop','/commission','/about','/cart','/status']){await go(route);await lang('ID');texts[route]=await page.locator('main').innerText();await lang('EN');await lang('ID')};fs.writeFileSync(OUT+'/indonesian-pages.json',JSON.stringify(texts,null,2));ok('Repeated language changes across seven public routes without DOM errors');
 await go('/commission');await lang('EN');await page.getByLabel('Name',{exact:true}).fill('New');await page.getByLabel('Contact',{exact:true}).fill('new@example.com');await page.locator('#style').selectOption('anime');await lang('ID');assert.equal(await page.getByLabel('Nama',{exact:true}).inputValue(),'New');assert.equal(await page.locator('#style').inputValue(),'anime');await lang('EN');assert.equal(await page.getByLabel('Name',{exact:true}).inputValue(),'New');ok('Language switch preserves form input and option values');
 await page.locator('#main-ref').setInputFiles(ROOT+'/src/assets/artworks/traditional/jasper.jpeg');await page.getByAltText('Preview Main Reference Photo').waitFor();await lang('ID');await page.getByAltText('Pratinjau Foto Referensi Utama').waitFor();ok('Upload labels and preview alt text translated');
 await go('/shop');await lang('EN');await page.locator('article').filter({has:page.getByRole('heading',{name:'Jasper',exact:true})}).getByRole('button',{name:'Add to Cart',exact:true}).click();await go('/checkout');
 await page.getByLabel('Full Name',{exact:true}).fill('New');await page.getByLabel('Email',{exact:true}).fill('new@example.com');await page.getByLabel('Address',{exact:true}).fill('New');await page.getByLabel('City',{exact:true}).fill('New');await page.getByLabel('Province',{exact:true}).fill('Bali');await page.getByLabel('Postal Code',{exact:true}).fill('81119');await lang('ID');assert.equal(await page.getByLabel('Nama Lengkap',{exact:true}).inputValue(),'New');await button('Lanjut ke Pembayaran').click();await page.waitForURL('**/payment/*');let data=await db();const order=data.orders[0];assert.equal(order.customer.name,'New');assert.equal(order.shipping.address,'New');assert.equal(data.artworks.find(a=>a.id===14).status,'available');ok('Checkout preserves user text and does not mark unpaid artwork sold');
 await lang('EN');await page.locator('label').filter({has:page.getByRole('radio',{name:/Bank Transfer/})}).click();await page.locator('#payment-proof').setInputFiles(ROOT+'/src/assets/artworks/traditional/jasper.jpeg');await page.getByAltText('Preview Payment Proof').waitFor();await button('Submit Payment Proof').click();assert.equal((await db()).orders[0].paymentStatus,'waiting-verification');ok('Proof submitted while original remains unsold until verification');
 await go('/admin/login');await page.getByLabel('Username',{exact:true}).fill('admin');await page.getByLabel('Password',{exact:true}).fill('artura123');await button('Login to Admin Panel').click();await page.waitForURL('**/admin/dashboard');
 await go('/admin/orders/'+order.id);
 await page.evaluate(()=>{const original=Storage.prototype.setItem;window.restoreStorage=()=>Storage.prototype.setItem=original;Storage.prototype.setItem=function(k,v){if(k==='artura.store.v2')throw new DOMException('Full','QuotaExceededError');return original.call(this,k,v)}});await button('Verify Payment').click();assert.equal((await db()).orders[0].paymentStatus,'waiting-verification');assert.equal((await db()).artworks.find(a=>a.id===14).status,'available');await page.evaluate(()=>window.restoreStorage());ok('Quota failure cannot partially save Paid or Sold');
 await button('Verify Payment').click();data=await db();assert.equal(data.orders[0].paymentStatus,'paid');assert.equal(data.artworks.find(a=>a.id===14).status,'sold');ok('Payment verification atomically changes artwork to Sold');
 await go('/shop');let card=page.locator('article').filter({has:page.getByRole('heading',{name:'Jasper',exact:true})});assert.equal(await card.getByRole('button',{name:'Sold',exact:true}).isDisabled(),true);assert.equal(await card.getByRole('button',{name:'Add to Cart',exact:true}).count(),0);await lang('ID');assert.equal(await card.getByRole('button',{name:'Terjual',exact:true}).isDisabled(),true);await page.screenshot({path:OUT+'/shop-id-sold.png',fullPage:true});await page.reload();assert.equal(await card.getByRole('button',{name:'Terjual',exact:true}).isDisabled(),true);ok('Sold/Terjual persists after refresh and blocks cart button');
 await go('/artwork/jasper');assert.equal(await button('Terjual').first().isDisabled(),true);await go('/order/'+order.id);await page.getByText('New',{exact:true}).first().waitFor();assert.ok(!(await page.locator('main').innerText()).includes('Baru'));await go('/admin/payments');await page.getByRole('cell',{name:'New',exact:true}).waitFor();ok('Detail stock and receipt preserve names/addresses such as New');
 await lang('EN');await go('/admin/artworks/edit/14');await page.locator('select').filter({has:page.locator('option[value="sold"]')}).selectOption('available');await button('Save Artwork').click();await page.getByText('A sold original artwork cannot be made available again.',{exact:true}).waitFor();assert.equal((await db()).artworks.find(a=>a.id===14).status,'sold');ok('Admin cannot relist a sold one-off original');
 await go('/artwork/waguri');await button('Add to Cart').first().click();await go('/checkout');await page.getByLabel('Full Name',{exact:true}).fill('Buyer');await page.getByLabel('Email',{exact:true}).fill('buyer@example.com');for(const [label,value]of [['Address','Street 1'],['City','Singaraja'],['Province','Bali'],['Postal Code','81119']])await page.getByLabel(label,{exact:true}).fill(value);await button('Continue to Payment').click();await page.waitForURL('**/payment/*');const pending=(await db()).orders[0];
 await go('/artwork/waguri');await button('Add to Cart').first().click();await go('/checkout');await page.getByLabel('Full Name',{exact:true}).fill('Buyer 2');await page.getByLabel('Email',{exact:true}).fill('buyer2@example.com');for(const [label,value]of [['Address','Street 2'],['City','Singaraja'],['Province','Bali'],['Postal Code','81119']])await page.getByLabel(label,{exact:true}).fill(value);await button('Continue to Payment').click();await page.getByText('This artwork already has an active order. Complete or cancel that order first.',{exact:true}).waitFor();assert.equal((await db()).orders.length,2);ok('Duplicate checkout for a reserved original blocked');
 await go('/admin/orders/'+pending.id);await button('Cancel Order').click();await go('/payment/'+pending.id);assert.equal(await button('Submit Payment Proof').count(),0);assert.equal((await db()).artworks.find(a=>a.id===20).status,'available');ok('Cancelled unpaid order releases stock and blocks proof');
 for(const route of ['/admin/dashboard','/admin/artworks','/admin/artworks/add','/admin/commissions','/admin/orders','/admin/payments','/admin/reviews','/admin/pricing','/admin/profile','/admin/settings']){await go(route);await lang('ID');texts[route]=await page.locator('main').innerText();await lang('EN');}
 fs.writeFileSync(OUT+'/indonesian-pages.json',JSON.stringify(texts,null,2));ok('Admin pages translated in both languages');
 await go('/admin/pricing');await page.locator('input[type=number]').first().fill('-10');await button('Save Pricing').click();assert.equal((await db()).pricing.basePrices.digital.realistic,120000);ok('Negative price cannot be saved');
 await page.setViewportSize({width:390,height:844});for(const route of ['/','/shop','/commission','/status','/admin/pricing']){await go(route);await lang('ID');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'overflow '+route)}await go('/commission');await page.locator('#main-ref').scrollIntoViewIfNeeded();await page.screenshot({path:OUT+'/commission-id-mobile.png'});ok('Mobile layout 390px has no page overflow on five key routes');
 await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'id');ok('Language preference persists on reload');
 const other=await context.newPage();other.on('pageerror',e=>errors.push(e.message));await other.goto('/shop');await page.evaluate(()=>{const d=JSON.parse(localStorage.getItem('artura.store.v2'));d.artworks.find(a=>a.id===20).status='sold';localStorage.setItem('artura.store.v2',JSON.stringify(d))});await other.locator('article').filter({has:other.getByRole('heading',{name:'Waguri',exact:true})}).getByRole('button',{name:'Terjual',exact:true}).waitFor();await other.close();ok('Stock sync between browser tabs');
 const migration=await browser.newContext({baseURL:'http://127.0.0.1:5173'});const m=await migration.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto('/');await m.evaluate(order=>{localStorage.setItem('artura_orders',JSON.stringify([order]));localStorage.setItem('artura.language.v1','en')},{...order,paymentStatus:'paid',orderStatus:'processing'});await m.reload();await m.goto('/shop');assert.equal(await m.locator('article').filter({has:m.getByRole('heading',{name:'Jasper',exact:true})}).getByRole('button',{name:'Sold',exact:true}).isDisabled(),true);ok('Legacy paid orders repair missing Sold state');await m.evaluate(()=>{localStorage.setItem('artura_orders','null');localStorage.setItem('artura_artworks','{}');localStorage.setItem('artura_reviews','null')});await m.reload();await m.getByRole('heading',{name:'Jasper',exact:true}).waitFor();ok('Malformed localStorage collections recover without white screen');await migration.close();
 assert.deepEqual(errors,[]);ok('No uncaught browser JavaScript errors');fs.writeFileSync(OUT+'/report.json',JSON.stringify({passed,errors},null,2));
}catch(e){if(page)await page.screenshot({path:OUT+'/failure.png',fullPage:true}).catch(()=>{});throw e}finally{await browser.close();await new Promise(resolve=>server.httpServer.close(resolve))}
})().catch(e=>{console.error(e);process.exit(1)});
